### ISSUE TITLE
`gw` cannot start

### ISSUE THREAD

**Issue by ZihengSun** [ESIPFed/pygeoweaver#45]
(base) [zsun@hopper2 ~]$ gw
Traceback (most recent call last):
  File "/home/zsun/anaconda3/bin/gw", line 5, in <module>
    from pygeoweaver.__main__ import geoweaver
  File "/home/zsun/anaconda3/lib/python3.8/site-packages/pygeoweaver/__init__.py", line 5, in <module>
    setup_logging()
  File "/home/zsun/anaconda3/lib/python3.8/site-packages/pygeoweaver/log_config.py", line 29, in setup_logging
    logging.config.fileConfig(config_file)
AttributeError: module 'logging' has no attribute 'config'

**Comment by ZihengSun** [comment]
Fixed. Need to `import logging.config`
